### ISSUE TITLE
POTCAR

### ISSUE THREAD

**Issue by tkphd** [JMSkelton/VASP-GPU-Benchmarking#1]
I'm trying to run a small benchmark to test my CUDA VASP build. I copied `INCAR` and `KPOINTS` from `Benchmarks/GeTe/InputFiles/`, and copied `Benchmarks/GeTe/InputFiles/POSCAR_GeTe-128.vasp`
to `POSCAR`. But it seems that `POTCAR` was never checked in to the repository:

```
$ ./vasp
Using device 0 (rank 0, local rank 0, local size 1) : Tesla C2075
 running on    1 total cores
 distrk:  each k-point on    1 cores,    1 groups
 distr:  one band on    1 cores,    1 groups
 using from now: INCAR     
  
 *******************************************************************************
  You are running the GPU port of VASP! When publishing results obtained with
  this version, please cite:
   - M. Hacene et al., http://dx.doi.org/10.1002/jcc.23096
   - M. Hutchinson and M. Widom, http://dx.doi.org/10.1016/j.cpc.2012.02.017
  
  in addition to the usual required citations (see manual).
  
  GPU developers: A. Anciaux-Sedrakian, C. Angerer, and M. Hutchinson.
 *******************************************************************************
  
 vasp.5.4.4.18Apr17-6-g9f103f2a35 (build Nov  5 2018 12:49:02) complex           
 POSCAR found type information on POSCAR  Ge Te
 POSCAR found :  2 types and     128 ions
At line 386 of file pseudo.f90 (unit = 10)
Fortran runtime error: Cannot open file 'POTCAR': No such file or directory
```

If the file is still available, may we (the repo users) please have it?

Thanks :smile:

**Comment by JMSkelton** [comment]
Unfortunately, the `POTCAR` files are part of the `VASP` code, which means distributing them online is almost certainly a legal "grey area". I therefore don't include them in repositories just in case.

For reference, I used the `Ge` and `Te` potentials from the  `potpaw_PBE` dataset in these calculations; presuming you have a VASP license, e-mail me privately at jonathan.skelton[at]manchester[dot]ac[dot]uk and I'll send you the file directly
